kind: PersistentVolume
apiVersion: v1
metadata:
  name: pvc-nodejs-web-app
spec:
  capacity:
    storage: 1Gi
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0aeea8bd36b9037b7
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1716499011768-3822-ebs.csi.aws.com
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp3-csi
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.ebs.csi.aws.com/zone
              operator: In
              values:
                - us-east-2c
