kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nodejs-web-app
  namespace: nodejs-web-app-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem
