apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- patch: |- 
    - op: add
      path: /spec/generators/0/list
      value:
        elements: 
        - cluster: dev
          url: https://kubernetes.default.svc
          namespace: dev-baseline-demo
  target:
    kind: ApplicationSet
