apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pipelines-creation
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        namespace: php-hello
  template:
    metadata:
      name: '{{cluster}}-pipeline-creation'
    spec:
      source:
        repoURL: https://github.com/taiseerhussein/baseline-demo
        targetRevision: main
        path: tekton
      project: default
      destination:
        server: '{{url}}'
        namespace: openshift-gitops
      syncPolicy:
        automated:
          prune: true
          selfHeal: true