apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nodejs-web-demo
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      # The proper generator will be patched from the proper overlay directory
  template:
    metadata:
      name: '{{cluster}}-{{namespace}}-nodejs-web-demo'
    spec:
      source:
        repoURL: https://github.com/taiseerhussein/baseline-demo
        targetRevision: main
        path: kustomize/org-services/services/nodejs-web-demo/overlays/{{cluster}}
      project: default
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true