apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: service2
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      # The proper generator will be patched from the proper overlay directory
  template:
    metadata:
      name: '{{cluster}}-{{namespace}}-service2'
    spec:
      source:
        repoURL: https://github.com/uc2-io/demo2win
        targetRevision: main
        path: kustomize/org-services/services/service2/overlays/{{cluster}}
      project: default
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true