apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../org-services/demo2win/overlays/dev
# - ../../org-services/php-hello/overlays/dev
# - ../../org-services/namespace3/overlays/dev

# create namespaces appset. 
- ../../namespaces
#- ../../pipelines

