apiVersion: apps/v1
kind: Deployment
metadata:
   annotations:
    argocd.argoproj.io/sync-wave: "2"
   labels:
     app: php-hello
   name: php-hello
   namespace: dev-php-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-hello
  strategy: {}
  template:
    metadata:
      labels:
        app: php-hello
    spec:
      containers:
      - image: quay.io/tkhussein/php-hello:latest
        name: php-hello
        resources: {}
