apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: php-hello
  name: php-hello
  namespace: dev-php-hello
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: php-hello
    weight: 100
