apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../..baseline-demophp-hello/overlays/stage
- ../..baseline-demovalue-add/overlays/stage
- ../../backbase/overlays/stage


# Create sealed secret appsets
- ../../sealed-secrets/stage
